---

logging:
  level:
    org.springframework: INFO

server:
  port: 9125

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/psycho_testing_db
    username: postgres
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
